"""add_provider_credential_table

Revision ID: 14fc5ae9d93a
Revises: 4a34eacc4f22
Create Date: 2026-04-09 06:37:48.483354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fc5ae9d93a'
down_revision: Union[str, Sequence[str], None] = '4a34eacc4f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Creates the ProviderCredential table for the new provider-manager architecture.

    NOTE: This migration does NOT migrate data from legacy UserSettings fields.
    Data migration is handled lazily via the credential_resolver module:
    - New reads use ProviderCredential first, falling back to UserSettings
    - Legacy writes dual-write to both tables
    - Full migration can be done later via a background job or admin command

    TODO: After sufficient migration period, implement data migration script
    to move all credentials from UserSettings to ProviderCredential table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providercredential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('credential_key', sa.String(), nullable=True),
    sa.Column('endpoint_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    # Unique constraint: one credential per user per provider
    sa.UniqueConstraint('user_id', 'provider_name', name='uix_user_provider')
    )
    with op.batch_alter_table('providercredential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providercredential_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_providercredential_provider_type'), ['provider_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_providercredential_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providercredential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providercredential_user_id'))
        batch_op.drop_index(batch_op.f('ix_providercredential_provider_type'))
        batch_op.drop_index(batch_op.f('ix_providercredential_provider_name'))

    op.drop_table('providercredential')
    # ### end Alembic commands ###
