"""add waitlist table

Revision ID: 1b9a048349b4
Revises: c730d222f10d
Create Date: 2026-04-13 18:13:07.227456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1b9a048349b4'
down_revision: Union[str, Sequence[str], None] = 'c730d222f10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlistentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlistentry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlistentry_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlistentry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlistentry_email'))

    op.drop_table('waitlistentry')
    # ### end Alembic commands ###
