"""initial schema

Revision ID: 3f238f2fb55f
Revises:
Create Date: 2026-04-08 09:25:08.462161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3f238f2fb55f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "verification_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("verification_token_expires", sa.DateTime(), nullable=True),
        sa.Column("auth_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_user_google_id"), ["google_id"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_user_verification_token"),
            ["verification_token"],
            unique=False,
        )

    op.create_table(
        "campaign",
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RESEARCHING",
                "GENERATING",
                "AWAITING_APPROVAL",
                "COMPLETED",
                "FAILED",
                name="campaignstatus",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refreshtoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("refreshtoken", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refreshtoken_token"), ["token"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_refreshtoken_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "repurposejob",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("youtube_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("video_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("video_duration", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "EXTRACTING",
                "TRANSCRIBING",
                "GENERATING",
                "COMPLETED",
                "FAILED",
                name="repurposestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "tone_style",
            sa.Enum("FORMAL", "CASUAL", "FRIENDLY", name="tonestyle"),
            nullable=False,
        ),
        sa.Column(
            "target_platforms", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("transcript", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "transcript_segments", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("key_points", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum("FREE", "BASIC", "PRO", "ULTRA", name="plantier"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "CANCELED", "PAST_DUE", "TRIALING", name="subscriptionstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "paddle_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "paddle_subscription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("paddle_price_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("current_period_start", sa.DateTime(), nullable=True),
        sa.Column("current_period_end", sa.DateTime(), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscription_paddle_customer_id"),
            ["paddle_customer_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_paddle_subscription_id"),
            ["paddle_subscription_id"],
            unique=False,
        )

    op.create_table(
        "usagetracking",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("credits_used", sa.Integer(), nullable=False),
        sa.Column("bonus_credits", sa.Integer(), nullable=False),
        sa.Column("total_credits_used", sa.Integer(), nullable=False),
        sa.Column("total_images", sa.Integer(), nullable=False),
        sa.Column("total_videos", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "usersettings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("openai_api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("fal_api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "firecrawl_api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("heygen_api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("did_api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "default_llm_engine", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "default_image_engine", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "default_video_engine", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "default_ugc_engine", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("ugc_enabled", sa.Boolean(), nullable=False),
        sa.Column("ugc_avatar_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ugc_voice_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ollama_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("comfyui_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "agentlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("agent_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("COPY", "IMAGE", "VIDEO", name="assettype"), nullable=False
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asset_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "creditusagelog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("resource_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creditusagelog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creditusagelog_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creditusagelog_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "repurposecontent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum(
                "NAVER_BLOG",
                "X_THREAD",
                "INSTAGRAM",
                "BRUNCH",
                "NAVER_POST",
                "SHORT_CLIP",
                name="contentplatform",
            ),
            nullable=False,
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "content_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["repurposejob.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("repurposecontent")
    with op.batch_alter_table("creditusagelog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creditusagelog_user_id"))
        batch_op.drop_index(batch_op.f("ix_creditusagelog_date"))

    op.drop_table("creditusagelog")
    op.drop_table("asset")
    op.drop_table("agentlog")
    op.drop_table("usersettings")
    op.drop_table("usagetracking")
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscription_paddle_subscription_id"))
        batch_op.drop_index(batch_op.f("ix_subscription_paddle_customer_id"))

    op.drop_table("subscription")
    op.drop_table("repurposejob")
    with op.batch_alter_table("refreshtoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refreshtoken_user_id"))
        batch_op.drop_index(batch_op.f("ix_refreshtoken_token"))

    op.drop_table("refreshtoken")
    op.drop_table("campaign")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_verification_token"))
        batch_op.drop_index(batch_op.f("ix_user_google_id"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
