"""add_anthropic_google_groq_sadtalker_fields

Revision ID: 4a34eacc4f22
Revises: 6f8c42c776a1
Create Date: 2026-04-08 22:46:35.810374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a34eacc4f22"
down_revision: Union[str, Sequence[str], None] = "6f8c42c776a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usersettings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("anthropic_api_key", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("google_api_key", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("groq_api_key", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("sadtalker_url", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usersettings", schema=None) as batch_op:
        batch_op.drop_column("sadtalker_url")
        batch_op.drop_column("groq_api_key")
        batch_op.drop_column("google_api_key")
        batch_op.drop_column("anthropic_api_key")

    # ### end Alembic commands ###
