"""add_productphoto_pricing_ailabeling_models

Revision ID: 6f8c42c776a1
Revises: e1f272e618fa
Create Date: 2026-04-08 17:42:32.042029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6f8c42c776a1"
down_revision: Union[str, Sequence[str], None] = "e1f272e618fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productphoto",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column(
            "original_image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("bg_removed_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "REMOVING_BG",
                "GENERATING",
                "COMPLETED",
                "FAILED",
                name="productphotostatus",
            ),
            nullable=False,
        ),
        sa.Column("angles", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("results", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scene_prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
            name="fk_productphoto_campaign_id",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="fk_productphoto_user_id",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("productphoto", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_productphoto_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ai_disclosure",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="{}",
            )
        )

    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "billing_period",
                sa.Enum("MONTHLY", "ANNUAL", name="billingperiod"),
                nullable=False,
                server_default="MONTHLY",
            )
        )
        batch_op.alter_column(
            "tier",
            existing_type=sa.VARCHAR(length=5),
            type_=sa.Enum("FREE", "BASIC", "PRO", "ULTRA", "AGENCY", name="plantier"),
            existing_nullable=False,
        )

    with op.batch_alter_table("usagetracking", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "rolled_over_credits", sa.Integer(), nullable=False, server_default="0"
            )
        )

    with op.batch_alter_table("usersettings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ai_disclosure_enabled",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "ai_label_text",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="AI Generated",
            )
        )
        batch_op.add_column(
            sa.Column(
                "ai_label_position",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default="BOTTOM_RIGHT",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usersettings", schema=None) as batch_op:
        batch_op.drop_column("ai_label_position")
        batch_op.drop_column("ai_label_text")
        batch_op.drop_column("ai_disclosure_enabled")

    with op.batch_alter_table("usagetracking", schema=None) as batch_op:
        batch_op.drop_column("rolled_over_credits")

    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.alter_column(
            "tier",
            existing_type=sa.Enum(
                "FREE", "BASIC", "PRO", "ULTRA", "AGENCY", name="plantier"
            ),
            type_=sa.VARCHAR(length=5),
            existing_nullable=False,
        )
        batch_op.drop_column("billing_period")

    with op.batch_alter_table("asset", schema=None) as batch_op:
        batch_op.drop_column("ai_disclosure")

    with op.batch_alter_table("productphoto", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_productphoto_user_id"))

    op.drop_table("productphoto")
    # ### end Alembic commands ###
