"""autopilot_v2_fields_and_notification

Revision ID: 9202c54beac2
Revises: bb853d1fa2d8
Create Date: 2026-04-22 08:55:03.869729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9202c54beac2'
down_revision: Union[str, Sequence[str], None] = 'bb853d1fa2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('AUTOPILOT_COMPLETE', 'AUTOPILOT_FAILED', 'AUTOPILOT_DISABLED', 'CREDITS_LOW', 'APPROVAL_NEEDED', 'PUBLISH_COMPLETE', 'PUBLISH_FAILED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('autopilotrule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_publish', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('publish_connection_ids', sa.String(), nullable=True))

    with op.batch_alter_table('autopilotrunlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('publish_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autopilotrunlog', schema=None) as batch_op:
        batch_op.drop_column('publish_status')
        batch_op.drop_column('retry_count')

    with op.batch_alter_table('autopilotrule', schema=None) as batch_op:
        batch_op.drop_column('publish_connection_ids')
        batch_op.drop_column('auto_publish')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))

    op.drop_table('notification')
    # ### end Alembic commands ###
