"""add_advariant_teammember_adperformance_models

Revision ID: a5a1206d9edd
Revises: cce8ce5bac0d
Create Date: 2026-04-08 15:06:19.707607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a5a1206d9edd"
down_revision: Union[str, Sequence[str], None] = "cce8ce5bac0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teammember",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_owner_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("OWNER", "ADMIN", "EDITOR", "VIEWER", name="teamrole"),
            nullable=False,
        ),
        sa.Column(
            "invite_status",
            sa.Enum("PENDING", "ACCEPTED", "DECLINED", "EXPIRED", name="invitestatus"),
            nullable=False,
        ),
        sa.Column("invite_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("invited_at", sa.DateTime(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("teammember", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_teammember_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_teammember_invite_token"), ["invite_token"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_teammember_team_owner_id"), ["team_owner_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_teammember_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "adperformance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "FACEBOOK",
                "INSTAGRAM",
                "GOOGLE_ADS",
                "MANUAL",
                name="adperformancesource",
            ),
            nullable=False,
        ),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("conversions", sa.Integer(), nullable=False),
        sa.Column("spend_cents", sa.Integer(), nullable=False),
        sa.Column("revenue_cents", sa.Integer(), nullable=False),
        sa.Column("ctr", sa.Float(), nullable=True),
        sa.Column("cpc_cents", sa.Integer(), nullable=True),
        sa.Column("cpa_cents", sa.Integer(), nullable=True),
        sa.Column("roas", sa.Float(), nullable=True),
        sa.Column(
            "external_campaign_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "performance_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adperformance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_adperformance_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_adperformance_date"), ["date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_adperformance_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "advariant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("variant_label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("copy_headline", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("copy_body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("copy_cta", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("image_asset_id", sa.Integer(), nullable=True),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_control", sa.Boolean(), nullable=False),
        sa.Column(
            "variant_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["image_asset_id"],
            ["asset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("advariant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_advariant_campaign_id"), ["campaign_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("advariant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_advariant_campaign_id"))

    op.drop_table("advariant")
    with op.batch_alter_table("adperformance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adperformance_user_id"))
        batch_op.drop_index(batch_op.f("ix_adperformance_date"))
        batch_op.drop_index(batch_op.f("ix_adperformance_campaign_id"))

    op.drop_table("adperformance")
    with op.batch_alter_table("teammember", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_teammember_user_id"))
        batch_op.drop_index(batch_op.f("ix_teammember_team_owner_id"))
        batch_op.drop_index(batch_op.f("ix_teammember_invite_token"))
        batch_op.drop_index(batch_op.f("ix_teammember_email"))

    op.drop_table("teammember")
    # ### end Alembic commands ###
