"""add autopilot_rule and autopilot_run_log tables

Revision ID: bb853d1fa2d8
Revises: 9718c495ab82
Create Date: 2026-04-22 07:23:14.599264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb853d1fa2d8'
down_revision: Union[str, Sequence[str], None] = '9718c495ab82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autopilotrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cadence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('days_of_week', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_of_day', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_failure_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('product_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_kit_id', sa.Integer(), nullable=True),
    sa.Column('platform_targets', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_variations', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_timeout_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autopilotrule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autopilotrule_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_autopilotrule_user_id'), ['user_id'], unique=False)

    op.create_table('autopilotrunlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credits_estimated', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['autopilotrule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autopilotrunlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autopilotrunlog_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autopilotrunlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autopilotrunlog_rule_id'))

    op.drop_table('autopilotrunlog')
    with op.batch_alter_table('autopilotrule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autopilotrule_user_id'))
        batch_op.drop_index(batch_op.f('ix_autopilotrule_next_run_at'))

    op.drop_table('autopilotrule')
    # ### end Alembic commands ###
