"""migrate billing from paddle to lemonsqueezy

Revision ID: c730d222f10d
Revises: 48636ff32783
Create Date: 2026-04-13 12:06:26.032290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c730d222f10d"
down_revision: Union[str, Sequence[str], None] = "48636ff32783"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ls_customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "ls_subscription_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "ls_variant_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.alter_column(
            "tier",
            existing_type=sa.VARCHAR(length=6),
            type_=sa.Enum("FREE", "BASIC", "BYOK", "PRO", "ULTRA", name="plantier"),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("ix_subscription_paddle_customer_id"))
        batch_op.drop_index(batch_op.f("ix_subscription_paddle_subscription_id"))
        batch_op.create_index(
            batch_op.f("ix_subscription_ls_customer_id"),
            ["ls_customer_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_ls_subscription_id"),
            ["ls_subscription_id"],
            unique=False,
        )
        batch_op.drop_column("paddle_customer_id")
        batch_op.drop_column("paddle_price_id")
        batch_op.drop_column("paddle_subscription_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("paddle_subscription_id", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(sa.Column("paddle_price_id", sa.VARCHAR(), nullable=True))
        batch_op.add_column(
            sa.Column("paddle_customer_id", sa.VARCHAR(), nullable=True)
        )
        batch_op.drop_index(batch_op.f("ix_subscription_ls_subscription_id"))
        batch_op.drop_index(batch_op.f("ix_subscription_ls_customer_id"))
        batch_op.create_index(
            batch_op.f("ix_subscription_paddle_subscription_id"),
            ["paddle_subscription_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_subscription_paddle_customer_id"),
            ["paddle_customer_id"],
            unique=False,
        )
        batch_op.alter_column(
            "tier",
            existing_type=sa.Enum(
                "FREE", "BASIC", "BYOK", "PRO", "ULTRA", name="plantier"
            ),
            type_=sa.VARCHAR(length=6),
            existing_nullable=False,
        )
        batch_op.drop_column("ls_variant_id")
        batch_op.drop_column("ls_subscription_id")
        batch_op.drop_column("ls_customer_id")

    # ### end Alembic commands ###
