"""add_template_brandkit_publishing_models

Revision ID: cce8ce5bac0d
Revises: 3f238f2fb55f
Create Date: 2026-04-08 14:53:14.682998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cce8ce5bac0d"
down_revision: Union[str, Sequence[str], None] = "3f238f2fb55f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "industry",
            sa.Enum(
                "BEAUTY",
                "HEALTH",
                "FOOD",
                "IT_SAAS",
                "FASHION",
                "EDUCATION",
                "REAL_ESTATE",
                "FINANCE",
                "TRAVEL",
                "PET",
                name="templateindustry",
            ),
            nullable=False,
        ),
        sa.Column(
            "platform",
            sa.Enum(
                "INSTAGRAM",
                "FACEBOOK",
                "GOOGLE_ADS",
                "NAVER",
                "TIKTOK",
                name="templateplatform",
            ),
            nullable=False,
        ),
        sa.Column(
            "layout",
            sa.Enum(
                "SINGLE_IMAGE",
                "CAROUSEL",
                "VIDEO_COVER",
                "TEXT_OVERLAY",
                "SPLIT_VIEW",
                "PRODUCT_HERO",
                name="templatelayout",
            ),
            nullable=False,
        ),
        sa.Column("copy_template", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("style_config", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("preview_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_template_name"), ["name"], unique=False)

    op.create_table(
        "brandkit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("primary_color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("secondary_color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("accent_color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("font_heading", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("font_body", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tone_of_voice", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("brand_values", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("target_audience", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("guidelines", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("brandkit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_brandkit_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "publishconnection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("FACEBOOK", "INSTAGRAM", name="publishplatformtype"),
            nullable=False,
        ),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("account_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("publishconnection", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_publishconnection_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "publishlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "platform",
            sa.Enum("FACEBOOK", "INSTAGRAM", name="publishplatformtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PUBLISHING", "PUBLISHED", "FAILED", name="publishstatus"
            ),
            nullable=False,
        ),
        sa.Column(
            "external_post_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("external_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("asset_ids", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "publish_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("publishlog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_publishlog_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_publishlog_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("campaign", schema=None) as batch_op:
        batch_op.add_column(sa.Column("brand_kit_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("template_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_campaign_template_id", "template", ["template_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_campaign_brand_kit_id", "brandkit", ["brand_kit_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("campaign", schema=None) as batch_op:
        batch_op.drop_constraint("fk_campaign_brand_kit_id", type_="foreignkey")
        batch_op.drop_constraint("fk_campaign_template_id", type_="foreignkey")
        batch_op.drop_column("template_id")
        batch_op.drop_column("brand_kit_id")

    with op.batch_alter_table("publishlog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publishlog_user_id"))
        batch_op.drop_index(batch_op.f("ix_publishlog_campaign_id"))

    op.drop_table("publishlog")
    with op.batch_alter_table("publishconnection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_publishconnection_user_id"))

    op.drop_table("publishconnection")
    with op.batch_alter_table("brandkit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_brandkit_user_id"))

    op.drop_table("brandkit")
    with op.batch_alter_table("template", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_template_name"))

    op.drop_table("template")
    # ### end Alembic commands ###
