"""add_customvoice_customavatar_whitelabel_adunit_adservingevent

Revision ID: e1f272e618fa
Revises: f4d88193069e
Create Date: 2026-04-08 15:38:47.100278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e1f272e618fa"
down_revision: Union[str, Sequence[str], None] = "f4d88193069e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customavatar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "provider_avatar_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("preview_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("photo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PROCESSING", "READY", "FAILED", name="voiceclonestatus"
            ),
            nullable=False,
        ),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "avatar_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customavatar", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customavatar_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "customvoice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sample_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "provider_voice_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PROCESSING", "READY", "FAILED", name="voiceclonestatus"
            ),
            nullable=False,
        ),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customvoice", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customvoice_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "whitelabelconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("brand_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("logo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("favicon_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("primary_color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "secondary_color", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("custom_domain", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("custom_css", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email_from_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "email_from_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("hide_powered_by", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "config_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("whitelabelconfig", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_whitelabelconfig_user_id"), ["user_id"], unique=True
        )

    op.create_table(
        "adunit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embed_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "ACTIVE",
                "PAUSED",
                "EXPIRED",
                "ARCHIVED",
                name="adservingstatus",
            ),
            nullable=False,
        ),
        sa.Column("starts_at", sa.DateTime(), nullable=True),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("total_impressions", sa.Integer(), nullable=False),
        sa.Column("total_clicks", sa.Integer(), nullable=False),
        sa.Column("daily_impression_cap", sa.Integer(), nullable=True),
        sa.Column("daily_click_cap", sa.Integer(), nullable=True),
        sa.Column(
            "serving_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adunit", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_adunit_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_adunit_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "adservingevent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ad_unit_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ip_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_agent", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("referrer", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ad_unit_id"],
            ["adunit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("adservingevent", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_adservingevent_ad_unit_id"), ["ad_unit_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adservingevent", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adservingevent_ad_unit_id"))

    op.drop_table("adservingevent")
    with op.batch_alter_table("adunit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adunit_user_id"))
        batch_op.drop_index(batch_op.f("ix_adunit_campaign_id"))

    op.drop_table("adunit")
    with op.batch_alter_table("whitelabelconfig", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_whitelabelconfig_user_id"))

    op.drop_table("whitelabelconfig")
    with op.batch_alter_table("customvoice", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customvoice_user_id"))

    op.drop_table("customvoice")
    with op.batch_alter_table("customavatar", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customavatar_user_id"))

    op.drop_table("customavatar")
    # ### end Alembic commands ###
