"""add_apikey_predictioncomparison_scheduledpost_models

Revision ID: f4d88193069e
Revises: a5a1206d9edd
Create Date: 2026-04-08 15:20:26.727470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f4d88193069e"
down_revision: Union[str, Sequence[str], None] = "a5a1206d9edd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apikey",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scopes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("apikey", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_apikey_key_prefix"), ["key_prefix"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_apikey_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "predictioncomparison",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("predicted_ctr", sa.Float(), nullable=True),
        sa.Column("predicted_engagement_rate", sa.Float(), nullable=True),
        sa.Column("predicted_conversion_rate", sa.Float(), nullable=True),
        sa.Column("predicted_quality_score", sa.Float(), nullable=True),
        sa.Column("actual_ctr", sa.Float(), nullable=True),
        sa.Column("actual_engagement_rate", sa.Float(), nullable=True),
        sa.Column("actual_conversion_rate", sa.Float(), nullable=True),
        sa.Column("actual_impressions", sa.Integer(), nullable=True),
        sa.Column("actual_clicks", sa.Integer(), nullable=True),
        sa.Column("actual_conversions", sa.Integer(), nullable=True),
        sa.Column("accuracy_score", sa.Float(), nullable=True),
        sa.Column("ctr_deviation", sa.Float(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("predictioncomparison", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_predictioncomparison_campaign_id"),
            ["campaign_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_predictioncomparison_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "scheduledpost",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("publish_connection_id", sa.Integer(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SCHEDULED",
                "PUBLISHING",
                "PUBLISHED",
                "FAILED",
                "CANCELLED",
                name="schedulestatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "recurrence",
            sa.Enum("NONE", "DAILY", "WEEKLY", "MONTHLY", name="schedulerecurrence"),
            nullable=False,
        ),
        sa.Column("asset_ids", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("copy_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "schedule_metadata", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaign.id"],
        ),
        sa.ForeignKeyConstraint(
            ["publish_connection_id"],
            ["publishconnection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scheduledpost", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scheduledpost_campaign_id"), ["campaign_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduledpost_scheduled_at"), ["scheduled_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scheduledpost_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scheduledpost", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scheduledpost_user_id"))
        batch_op.drop_index(batch_op.f("ix_scheduledpost_scheduled_at"))
        batch_op.drop_index(batch_op.f("ix_scheduledpost_campaign_id"))

    op.drop_table("scheduledpost")
    with op.batch_alter_table("predictioncomparison", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_predictioncomparison_user_id"))
        batch_op.drop_index(batch_op.f("ix_predictioncomparison_campaign_id"))

    op.drop_table("predictioncomparison")
    with op.batch_alter_table("apikey", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_apikey_user_id"))
        batch_op.drop_index(batch_op.f("ix_apikey_key_prefix"))

    op.drop_table("apikey")
    # ### end Alembic commands ###
